### ISSUE TITLE
Works at debug mode only

### ISSUE THREAD

**Issue by Kajikoslav** [ekasetiawans/flutter_background_service#200] opened 2022-09-13 10:12 UTC
Its great plugin, but that works all fine only Flutter debug mode. When i create APK (i try all these: flutter build apk --release, 
flutter build apk --release --split-per-abi, flutter build apk) foregroung service is still at "Preparing" mode. I try example, my own app and everything i try changed if can (ignore battery optimalization etc.) , but still works fine debug mode only... please help me. I try Android 12 (Nokia X1) and 11 (Motorola fusion+)... ... and when I install debug APK is not working too. Tomas K.

**Comment by ekasetiawans** [comment] 2022-09-13 18:04
Closed as duplicate of #202

**Closed by ekasetiawans** 2022-09-13 18:04 UTC

**Comment by MoeezChohan1089** [comment] 2023-06-20 10:41
@pragma('vm:entry-point')
void onStart(ServiceInstance service) async {
  // Only available for flutter 3.0.0 and later
  DartPluginRegistrant.ensureInitialized();

  // For flutter prior to version 3.0.0
  // We have to register the plugin manually

  /// OPTIONAL when use custom notification
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
  FlutterLocalNotificationsPlugin();

  if (service is AndroidServiceInstance) {
    service.on('setAsForeground').listen((event) async{
      service.setAsForegroundService();
      // SharedPreferences prefs = await SharedPreferences.getInstance();
      // final storedRunningState = prefs.getBool('is_timer_running') ?? false;
      // if (storedRunningState == true) {
      //   CountdownTimerService().startTimer("foreground");
      // }
    });

    service.on('setAsBackground').listen((event) {
      service.setAsBackgroundService();
    });
  }

  service.on('stopService').listen((event) {
    service.stopSelf();
  });

  // bring to foreground
  Timer.periodic(const Duration(milliseconds: 500), (timer) async {
    if (service is AndroidServiceInstance) {
      if (await service.isForegroundService()) {

        await Future.delayed(Duration(seconds: 1)); // Add a delay before retrieving the value

        SharedPreferences prefs = await SharedPreferences.getInstance();

        // Retrieve the value from SharedPreferences
        final timerDuration = prefs.getInt('timer_duration') ?? 0;
        print('FLUTTER BACKGROUND SERVICE with shared Preference: $timerDuration');


        /// OPTIONAL for use custom notification
        /// the notification id must be equals with AndroidConfiguration when you call configure() method.
        flutterLocalNotificationsPlugin.show(
          888,
          'Baby Tracker',
          'Sleeping is in progress',
          const NotificationDetails(
            android: AndroidNotificationDetails(
              'my_foreground',
              'MY FOREGROUND SERVICE',
              icon: '@mipmap/ic_launcher',
              ongoing: true,
            ),
          ),
        );
        // if you don't using custom notification, uncomment this
        // service.setForegroundNotificationInfo(
        //   title: "My App Service",
        //   content: "Updated at ${DateTime.now()}",
        // );
      }
    }
    /// you can see this log in logcat
    print('FLUTTER BACKGROUND SERVICE: ${DateTime.now()}');
  });
}

Hy i am using shared_preference of countdown timer in background service onStart function when i run it in debug mode then it works correct and when i run it on release mode then it does not work it show 0,0,0,0 countdown and in debug correct countdown like 1,2,3,4,5 and so on please tell how i can solve this issue
