### ISSUE TITLE
Unable to use any other flutter plugin in background

### ISSUE THREAD

**Issue by paraslamsong** [ekasetiawans/flutter_background_service#99] opened 2022-02-15 11:04 UTC
Unhandled Exception: MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite)

When ever trying to use plugin in background process on iOS is giving MissingPluginException.
Android is working fine

 flutter_background_service: ^0.2.2
platform: ios

**Comment by Abdullah104** [comment] 2022-02-15 23:14
The same issue happens to me.
In my case, it was different packages but the error is the same.

**Comment by ekasetiawans** [comment] 2022-02-16 23:43
Hi everyone, sorry for the delay.
I have published version 0.2.5 to fix this issue.

To registering plugis please see example: https://github.com/ekasetiawans/flutter_background_service/blob/master/example/ios/Runner/AppDelegate.swift

Note that, only plugins that doesn't require UI allowed.
If you wish to use shared_preferences or any other plugins that implements Dart plugin registration have a look :
https://github.com/flutter/flutter/issues/98591
https://github.com/flutter/flutter/issues/98473

**Comment by ekasetiawans** [comment] 2022-02-17 12:46
closing this because it's a duplicate of #89

**Closed by ekasetiawans** 2022-02-17 12:46 UTC
