### ISSUE TITLE
How to change the notification icon

### ISSUE THREAD

**Issue by dangabdolfo** [ekasetiawans/flutter_background_service#159] opened 2022-05-28 07:13 UTC
Hi,

I try to change the notification icon in my app but I cannot do it.
I have created a new icon named "ic_bg_service_small" in the Android project but my icon is never loaded.

Can you help me?

Regards,
Daniel

**Comment by ekasetiawans** [comment] 2022-05-28 07:14
duplicate of https://github.com/ekasetiawans/flutter_background_service/issues/86

**Closed by ekasetiawans** 2022-05-28 07:14 UTC
