### ISSUE TITLE
Devices don't lock when service is running

### ISSUE THREAD

**Issue by insertjokehere** [ekasetiawans/flutter_background_service#157] opened 2022-05-27 03:50 UTC
Thanks for your awesome plugin!

I've implemented a foreground service on Android, but in my testing I have noticed that devices won't lock automatically or even dim their screens when the service is running. It appears that this is caused by this library acquiring a full wake lock:

https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service_android/android/src/main/java/id/flutter/flutter_background_service/BackgroundService.java#L53-L62

According to the [docs](https://developer.android.com/reference/android/os/PowerManager#FULL_WAKE_LOCK), a full wake lock "Ensures that the screen and keyboard backlight are on at full brightness".

It looks like this was introduced in https://github.com/ekasetiawans/flutter_background_service/pull/92 - is it possible to override this behavior?

**Comment by ekasetiawans** [comment] 2022-05-27 03:56
hi @insertjokehere that seems to be the cause, maybe we can add a Method Channel to release the lock when the flutter engine runs successfully.

**Comment by ekasetiawans** [comment] 2022-05-27 10:25
@insertjokehere I have published 2.1.1 to fix this issue. Could you confirm if it's solved?

**Comment by insertjokehere** [comment] 2022-05-27 10:44
Thanks for the quick turn around, I'll let you know how it goes when I have
a chance to test next week.

**Comment by insertjokehere** [comment] 2022-05-29 22:37
Hi,

Looking at the fix https://github.com/ekasetiawans/flutter_background_service/commit/c0830250b90a1ba6e2543a1bb25a13fba59a56b7 it seems like the library still acquires a full wake lock when the background service starts, but releases it after 10 minutes, or when the main application interacts with the service.

A couple of questions:
1. Does this mean that if the the service is set to start automatically at boot, when the phone turns on screen and CPU sleeping will be disabled for 10 minutes unless the user opens the app?
2. Why does this library need a full wake lock in the first place? @mohammedhasna2015 - what issue were you fixing with #92?

**Comment by ekasetiawans** [comment] 2022-05-30 00:07
@insertjokehere I added the timeout just for backup. The wakelock will be released when the flutter engine is started. You can find the release command here https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service_android/android/src/main/java/id/flutter/flutter_background_service/BackgroundService.java at line 253

**Comment by insertjokehere** [comment] 2022-06-03 00:08
> The wakelock will be released when the flutter engine is started

Thats great, thanks for clarifying.

I guess my question is more why does the library need a full wake lock in the first place? Full wake lock is a really extreme lock to acquire - it turns the screen on full brightness, stops it from turning off at all and locks the CPU into full power mode. Before #92, the library acquired a partial wake lock that keeps the CPU on but does let it throttle down if needed, why was that insufficient? Would partial wake lock + the new timeout logic work? Or is there some reason why a full wake lock is needed in order to make sure the service starts properly?

**Comment by ekasetiawans** [comment] 2022-06-03 00:32
@insertjokehere afaik, we need wake lock for making boot receiver works. If you have any other strategy, feel free to make a pull request. :)

**Comment by insertjokehere** [comment] 2022-06-03 01:39
Ah, makes sense. Thanks!

**Comment by iovasquez** [comment] 2022-06-06 13:38
This problem seems to also exist in iOS. I tested on an iPhone with the latest version of this package. Swift not being my cup of tea, even after reading the code, I am not certain why.

**Comment by ekasetiawans** [comment] 2022-06-06 23:41
@iovasquez That's weird, we don't do a wakelock like we have done on Android.

**Comment by iovasquez** [comment] 2022-06-08 14:17
Yes, after talking with my team: it was a miscommunication of which platform was being tested.

Thank you for your quick answer!

**Comment by jakeump** [comment] 2022-06-14 03:15
Hi @ekasetiawans 
I was glad to see this is an open issue. I am having the same issue; I have the wakelock plugin, and I have that tied to a setting to "keep screen on." Before I started using this package (it's fantastic btw), it worked perfectly. I'm finding that after I integrated background service into my project, the screen is always staying on and not even dimming.

**Comment by ekasetiawans** [comment] 2022-06-14 13:29
I just released flutter_background_service:^2.1.3 to fix this issue, please re-open this issue if the problem persists.

**Closed by ekasetiawans** 2022-06-14 13:29 UTC

**Comment by Grand-87** [comment] 2022-06-15 07:37
I have tested your fix on
```
-Samsung Galaxy S10 | Android 12
-Huawei Mate 20 lite | Android 10
-Blackberry Key2 | Android 8.1
```
and everything works **great**, thanks for your work!

I'm curious, can you tell in a few words what was the problem?

**Comment by ekasetiawans** [comment] 2022-06-15 09:04
@Grand-87 the wake lock acquired multiple times by the watchdog receiver but only released once. So, I move the acquire command to the correct location to make sure it's called once.
