### ISSUE TITLE
(Android) Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by anhpt1991** [ekasetiawans/flutter_background_service#101] opened 2022-02-17 03:03 UTC
Hello sir,
I want to record video via camera  interval in the onStart() of  back ground service then when  i call  await availableCameras() in onStart(), i always get the error message:
Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera).
![image](https://user-images.githubusercontent.com/84487874/154397382-6a6a15ba-f329-49a9-9e37-a86463cd07e9.png)
![image](https://user-images.githubusercontent.com/84487874/154397640-5ae220c1-7d96-48ba-a8d7-9116c0841db1.png)
![image](https://user-images.githubusercontent.com/84487874/154397761-3ea156d3-338b-4936-b2f7-7de20b2d7b47.png)

**Comment by ekasetiawans** [comment] 2022-02-17 12:45
duplicate of #89 
duplicate of #99

**Closed by ekasetiawans** 2022-02-17 12:45 UTC

**Comment by X-SLAYER** [comment] 2022-03-23 15:16
did you find any solution to use camera on background cuz i have the same problem
