### ISSUE TITLE
Stream builder data arrive in debug but not on release

### ISSUE THREAD

**Issue by MarsTheMan** [ekasetiawans/flutter_background_service#205] opened 2022-09-15 20:52 UTC
On iOS and debug the stream builder gets data from isolate to the UI. On release I stream builder gets no data and the activity indicator keeps loading.
Any advice?

**Comment by ekasetiawans** [comment] 2022-09-16 03:11
Could you provide a minimal reproducible sample project?

**Comment by MarsTheMan** [comment] 2022-09-16 06:49
`Future<void> initializeTimerService() async {
  final service = FlutterBackgroundService();
  await service.configure(
    androidConfiguration: AndroidConfiguration(
      // this will be executed when app is in foreground or background in separated isolate
      onStart: timerStart,

      // auto start service
      autoStart: true,
      isForegroundMode: true,
    ),
    iosConfiguration: IosConfiguration(
      // auto start service
      autoStart: true,

      // this will be executed when app is in foreground in separated isolate
      onForeground: timerStart,

      // you have to enable background fetch capability on xcode project
      onBackground: onIosBackground,
    ),
  );
  await service.startService();
}`

`void timerStart(ServiceInstance service) async {
  // Only available for flutter 3.0.0 and later
  DartPluginRegistrant.ensureInitialized();
  final apiNewController = Get.put(ApiNewController());
  Timer timer;
  // For flutter prior to version 3.0.0
  // We have to register the plugin manually

  // SharedPreferences preferences = await SharedPreferences.getInstance();
  // await preferences.setString("hello", "world");

  if (service is AndroidServiceInstance) {
    service.on('setAsForeground').listen((event) {
      service.setAsForegroundService();
    });

    service.on('setAsBackground').listen((event) {
      service.setAsBackgroundService();
    });
  }

  service.on('stopService').listen((event) {
    service.stopSelf();
    if (kDebugMode) {
      print('service stopped');
    }
  });
  double charge;
  int seconds;
  int minutes;
  int hours;
  if (apiNewController.isActiveRent.value) {
    if (kDebugMode) {
      print(apiNewController.isActiveRent.value.toString());
    }
    var timePassed = apiNewController.activeRentTime.value.inSeconds;
    seconds = timePassed;
    charge = (((timePassed / 60).ceil()) * 0.2) + 1.0;
    if (seconds >= 60) {
      minutes = seconds ~/ 60;
      seconds = 0;
      if (minutes >= 60) {
        hours = minutes ~/ 60;
        minutes = 0;
      }
    }
  } else {
    seconds = 0;
    minutes = 0;
    hours = 0;
    charge = 1.20;
  }
  timer = Timer.periodic(const Duration(seconds: 1), (timer) {
    seconds++;
    if (seconds == 60) {
      seconds = 0;
      minutes++;
      charge += 0.20;
      if (minutes == 60) {
        minutes = 0;
        hours++;
      }
    }
    service.invoke(
      'update',
      {
        "seconds": seconds,
        "minutes": minutes,
        "hours": hours,
        "charge": charge
      },
    );
  });`

**Comment by MarsTheMan** [comment] 2022-09-16 06:51
`Future<void> initializeTimerService() async {
  final service = FlutterBackgroundService();
  await service.configure(
    androidConfiguration: AndroidConfiguration(
      // this will be executed when app is in foreground or background in separated isolate
      onStart: timerStart,

      // auto start service
      autoStart: true,
      isForegroundMode: true,
    ),
    iosConfiguration: IosConfiguration(
      // auto start service
      autoStart: true,

      // this will be executed when app is in foreground in separated isolate
      onForeground: timerStart,

      // you have to enable background fetch capability on xcode project
      onBackground: onIosBackground,
    ),
  );
  await service.startService();
}`

`void timerStart(ServiceInstance service) async {
  // Only available for flutter 3.0.0 and later
  DartPluginRegistrant.ensureInitialized();
  final apiNewController = Get.put(ApiNewController());
  Timer timer;
  // For flutter prior to version 3.0.0
  // We have to register the plugin manually

  // SharedPreferences preferences = await SharedPreferences.getInstance();
  // await preferences.setString("hello", "world");

  if (service is AndroidServiceInstance) {
    service.on('setAsForeground').listen((event) {
      service.setAsForegroundService();
    });

    service.on('setAsBackground').listen((event) {
      service.setAsBackgroundService();
    });
  }

  service.on('stopService').listen((event) {
    service.stopSelf();
    if (kDebugMode) {
      print('service stopped');
    }
  });
  double charge;
  int seconds;
  int minutes;
  int hours;
  if (apiNewController.isActiveRent.value) {
    if (kDebugMode) {
      print(apiNewController.isActiveRent.value.toString());
    }
    var timePassed = apiNewController.activeRentTime.value.inSeconds;
    seconds = timePassed;
    charge = (((timePassed / 60).ceil()) * 0.2) + 1.0;
    if (seconds >= 60) {
      minutes = seconds ~/ 60;
      seconds = 0;
      if (minutes >= 60) {
        hours = minutes ~/ 60;
        minutes = 0;
      }
    }
  } else {
    seconds = 0;
    minutes = 0;
    hours = 0;
    charge = 1.20;
  }
  timer = Timer.periodic(const Duration(seconds: 1), (timer) {
    seconds++;
    if (seconds == 60) {
      seconds = 0;
      minutes++;
      charge += 0.20;
      if (minutes == 60) {
        minutes = 0;
        hours++;
      }
    }
    service.invoke(
      'update',
      {
        "seconds": seconds,
        "minutes": minutes,
        "hours": hours,
        "charge": charge
      },
    );
  });`

**Comment by MarsTheMan** [comment] 2022-09-16 12:28
I think its a device problem. But its the same on iPhone 11 Pro and Realme rmx3210

**Comment by VladlenRnd** [comment] 2022-09-19 10:32
I have this problem with android device on release version.

Method `onStart` not called on release, but debug it is work fine

I thought this should have been fixed in version 2.2.0 based on these issues.
[https://github.com/ekasetiawans/flutter_background_service/issues/202](url)

But for me it doesn't work :(

I used
flutter_background_service: ^2.3.5

[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.18)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by ekasetiawans** [comment] 2022-09-19 11:20
> `Future initializeTimerService() async { final service = FlutterBackgroundService(); await service.configure( androidConfiguration: AndroidConfiguration( // this will be executed when app is in foreground or background in separated isolate onStart: timerStart,
> 
> ```
>   // auto start service
>   autoStart: true,
>   isForegroundMode: true,
> ),
> iosConfiguration: IosConfiguration(
>   // auto start service
>   autoStart: true,
> 
>   // this will be executed when app is in foreground in separated isolate
>   onForeground: timerStart,
> 
>   // you have to enable background fetch capability on xcode project
>   onBackground: onIosBackground,
> ),
> ```
> 
> ); await service.startService(); }
> 
> void timerStart(ServiceInstance service) async { // Only available for flutter 3.0.0 and later DartPluginRegistrant.ensureInitialized(); final apiNewController = Get.put(ApiNewController()); Timer timer; // For flutter prior to version 3.0.0 // We have to register the plugin manually
> 
> // SharedPreferences preferences = await SharedPreferences.getInstance(); // await preferences.setString("hello", "world");
> 
> if (service is AndroidServiceInstance) { service.on('setAsForeground').listen((event) { service.setAsForegroundService(); });
> 
> ```
> service.on('setAsBackground').listen((event) {
>   service.setAsBackgroundService();
> });
> ```
> 
> }
> 
> service.on('stopService').listen((event) { service.stopSelf(); if (kDebugMode) { print('service stopped'); } }); double charge; int seconds; int minutes; int hours; if (apiNewController.isActiveRent.value) { if (kDebugMode) { print(apiNewController.isActiveRent.value.toString()); } var timePassed = apiNewController.activeRentTime.value.inSeconds; seconds = timePassed; charge = (((timePassed / 60).ceil()) * 0.2) + 1.0; if (seconds >= 60) { minutes = seconds ~/ 60; seconds = 0; if (minutes >= 60) { hours = minutes ~/ 60; minutes = 0; } } } else { seconds = 0; minutes = 0; hours = 0; charge = 1.20; } timer = Timer.periodic(const Duration(seconds: 1), (timer) { seconds++; if (seconds == 60) { seconds = 0; minutes++; charge += 0.20; if (minutes == 60) { minutes = 0; hours++; } } service.invoke( 'update', { "seconds": seconds, "minutes": minutes, "hours": hours, "charge": charge }, ); });`

thanks for the code, but I minimal sample project that published to github will more helped me for investigating the cause. Could you provide the example project?

**Comment by MarsTheMan** [comment] 2022-09-20 07:53
https://github.com/MarsTheMan/service_timer

**Comment by ekasetiawans** [comment] 2022-09-20 11:37
@MarsTheMan could you try to add `@pragma('vm:entry-point')` in driving_controller.dart at line 165 (before the `timerStart` method).

**Comment by VladlenRnd** [comment] 2022-09-20 18:41
@ekasetiawans 
I did as you suggested. 
It works!

**Comment by MarsTheMan** [comment] 2022-09-20 21:49
@ekasetiawans I can confirm that it works for both Android and iOS

**Closed** 2022-09-21 00:28 UTC
