### ISSUE TITLE
shared_preferences/flutter_secure_storage work incorrectly

### ISSUE THREAD

**Issue by SavchenkoAndriy** [ekasetiawans/flutter_background_service#206] opened 2022-09-15 21:29 UTC
Appeared after the update. When i run "onStart" and write data to storage. I am trying to get this data for display in application, but it does not match the data that exists in "onStart". When I restart the application, the data that was saved in "onStart" appears in the application. But the new ones are not displayed again until the next restart. flutter 3.0.5

**Comment by ekasetiawans** [comment] 2022-09-15 23:39
Could you provide a reproducible sample project?

**Comment by ekasetiawans** [comment] 2022-09-16 00:48
for shared_preferences you should call `reload()` method before you can get the data.
https://pub.dev/documentation/shared_preferences/latest/shared_preferences/SharedPreferences/reload.html

**Comment by SavchenkoAndriy** [comment] 2022-09-16 07:43
Future<void> addLocation(Info info) async {
  List<Info> list = await getLocations();
  list.add(info);
  List newList = list.map((e) => e.toMap()).toList();
  SharedPreferences shared = await SharedPreferences.getInstance();
  shared.setString('location_list', jsonEncode(newList));
}

Future<List<Info>> getLocations() async {
  SharedPreferences shared = await SharedPreferences.getInstance();
  String? list = shared.getString('location_list');
  return list != null ? _dataProcessed(jsonDecode(list) as List<dynamic>) : [];
}

List<Info> dataProcessed(List infoList) {
  final List<Info> list = <Info>[];
  for (final Map<String, dynamic> item in infoList) {
    list.add(Info.fromMap(item));
  }
  return list;
}

class Info {
  final DateTime time;
  final double latitude;
  final double longitude;

  Info({
    required this.time,
    required this.longitude,
    required this.latitude,
  });

  Map<String, String> toMap() {
    return {
      'time': time.toString(),
      'latitude': latitude.toString(),
      'longitude': longitude.toString(),
    };
  }

  factory Info.fromMap(Map<String, dynamic> map) {
    return Info(
      time: DateTime.parse(map['time']!),
      latitude: double.parse(map['latitude']!),
      longitude: double.parse(map['longitude']!),
    );
  }
}

**Comment by SavchenkoAndriy** [comment] 2022-09-16 07:43
when I run "onStart" I call every 10 seconds to determine the coordinates and write them with "addLocation". and in the app itself I call "getLocations"

**Comment by SavchenkoAndriy** [comment] 2022-09-16 07:43
i tried your option, it doesn't work either

**Comment by ekasetiawans** [comment] 2022-09-16 11:58
@SavchenkoAndriy since 2.3.0 the background service (android) is running on it's own process, it's just like you running 2 different app. So you need to call like this

```dart
final sp = await SharedPreferences.getInstace();
await sp.reload(); // this is needed to get the latest data from the host

final data = sp.getString('mydata');
```

**Comment by SavchenkoAndriy** [comment] 2022-09-17 16:09
`Future<void> addLocation(Info info) async {
  List<Info> list = await getLocations();
  list.add(info);
  List newList = list.map((e) => e.toMap()).toList();
  SharedPreferences shared = await SharedPreferences.getInstance();
  await shared.reload();
  shared.setString('location_list', jsonEncode(newList));
}

Future<List<Info>> getLocations() async {
  SharedPreferences shared = await SharedPreferences.getInstance();
  await shared.reload();
  String? list = shared.getString('location_list');
  return list != null ? _dataProcessed(jsonDecode(list) as List<dynamic>) : [];
}

List<Info> _dataProcessed(List infoList) {
  final List<Info> list = <Info>[];
  for (final Map<String, dynamic> item in infoList) {
    list.add(Info.fromMap(item));
  }
  return list;
}`

it still doesn't work

**Comment by ekasetiawans** [comment] 2022-09-19 01:12
<img width="893" alt="image" src="https://user-images.githubusercontent.com/20693888/190936313-e32f0cf8-18da-43c3-ab6b-dd8c7916fef5.png">

After some research, I found that SharedPreferences is not supported to Multi Process, here is the documentation https://developer.android.com/reference/android/content/SharedPreferences.html

So, we need to move to another storage that supports multi process.

**Comment by ekasetiawans** [comment] 2022-09-20 00:23
I'd reverted to the single process on 2.4.0

**Comment by SavchenkoAndriy** [comment] 2022-09-20 12:01
Oh thank you. Very grateful to You! Will try it today.

**Comment by SavchenkoAndriy** [comment] 2022-09-20 18:26
i now have another problem. I have a timer that calls every 3 seconds. but it now calls once every 6 seconds 2 times almost at the same time.
D/BackgroundService(19825): Service already running, using existing service
I/flutter (19825): FLUTTER BACKGROUND SERVICE: 2022-09-20 21:25:38.878305
I/flutter (19825): FLUTTER BACKGROUND SERVICE: 2022-09-20 21:25:38.879586

**Comment by ekasetiawans** [comment] 2022-09-21 00:33
> I now have another problem. I have a timer that calls every 3 seconds. But it now calls once every 6 seconds 2 times almost at the same time.
> 
> D/BackgroundService(19825): Service already running, using existing service I/flutter (19825): FLUTTER BACKGROUND SERVICE: 2022-09-20 21:25:38.878305 I/flutter (19825): FLUTTER BACKGROUND SERVICE: 2022-09-20 21:25:38.879586

Please file to the another issue

**Comment by ekasetiawans** [comment] 2022-09-21 00:33
Closing this as resolved

**Closed by ekasetiawans** 2022-09-21 00:33 UTC

**Comment by Nedimko123** [comment] 2022-10-01 10:51
> @SavchenkoAndriy since 2.3.0 the background service (android) is running on it's own process, it's just like you running 2 different app. So you need to call like this
> 
> ```dart
> final sp = await SharedPreferences.getInstace();
> await sp.reload(); // this is needed to get the latest data from the host
> 
> final data = sp.getString('mydata');
> ```
> 
> if you don't call reload() then you will get cached data from the each isolate, not from the actual physical storage.

Thanks, it worked for my cubit instance, I was wondering why everything else worked but removing keys from sharedpreferences wasn't. Thanks, man!!

**Comment by Kesmi** [comment] 2023-04-17 06:46
@SavchenkoAndriy, If we used GetStorage then how to reload values in GetStorage()?
